// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0uMC2FtYOvo2AbMJHlzTkxi019YvZxz8',
    appId: '1:920149916714:android:6c2d6efaf97932695ed753',
    messagingSenderId: '920149916714',
    projectId: 'crud-95524',
    storageBucket: 'crud-95524.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJuBe3NXWCdmdRse4nOF5z6iluYSBeRSA',
    appId: '1:920149916714:ios:c72f223a7164e3b05ed753',
    messagingSenderId: '920149916714',
    projectId: 'crud-95524',
    storageBucket: 'crud-95524.firebasestorage.app',
    androidClientId: '920149916714-prdalhr8t3nmnkjhpv0r9g2ev9hkc8ui.apps.googleusercontent.com',
    iosClientId: '920149916714-40dv4fqbsjqvqsajmh5nvpkdql7u0b9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudSqliteProvider',
  );
}
